Resume/Models/ResumeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Resume.Web.Models
{
    public class ResumeViewModel
    {
        public string Name { get; set; }

        public string AddressStreet { get; set; }

        public string AddressCity { get; set; }

        public string AddressState { get; set; }

        public string AddressZip { get; set; }

    }
}

Resume/Controllers/ResumeController.cs
using AutoMapper;
using Model.IRepositories;
using Resume.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Resume.Web.Controllers
{
    public class ResumeController : Controller
    {
        //
        // GET: /Resume/
        private IResumeRepository resumeRepository;

        public ResumeController() { }

        public ResumeController(IResumeRepository resumeRepository)
        {
            this.resumeRepository = resumeRepository;
        }

        public ActionResult Index()
        {
            var indexViewModel = new ResumeIndexViewModel();
            indexViewModel.ResumeItems = Mapper.Map<IEnumerable<ResumeIndexItemViewModel>>(this.resumeRepository.All());
            return View(indexViewModel);
        }

        //
        // GET: /Resume/Details/5

        public ActionResult Details(int id)
        {
            var resumeVm = AutoMapper.Mapper.Map<ResumeViewModel>(resumeRepository.GetResumeById(id));
            return View(resumeVm);
        }

        //
        // GET: /Resume/Create

        public ActionResult Create()
        {
            var createModel = new ResumeCreateModel();
            return View(createModel);
        }

        //
        // POST: /Resume/Create

        [HttpPost]
        public ActionResult Create(ResumeCreateModel createModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Model.Resume createResume = new Model.Resume();
                    createResume.Name = createModel.Name;

                    resumeRepository.AddOrUpdateResume(createResume);

                    resumeRepository.Save();

                    return RedirectToAction("Edit", new { id = createResume.Id });
                }
                else
                {
                    return View(createModel);
                }
            }
            catch
            {
                return View(createModel);
            }
        }

        //
        // GET: /Resume/Edit/5

        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /Resume/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Resume/Delete/5

        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /Resume/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Resume/Views/Resume/Create.cshtml
@model Resume.Web.Models.ResumeCreateModel

@{
    ViewBag.Title = "Create";
}

<h2>Create New Resume</h2>
@using(Html.BeginForm())
{
    <div>Name</div>
    <div>@Html.EditorFor(m => m.Name)</div>
    <div>
        <button type="submit">Create</button>
    </div>
}

Resume/Views/Resume/Details.cshtml
@model Resume.Web.Models.ResumeViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>
<div>@Html.LabelFor(m => m.Name)</div>
<div>@Html.DisplayFor(m =>m.Name)</div>

Resume/Views/Resume/Index.cshtml
@model Resume.Web.Models.ResumeIndexViewModel
@{
    ViewBag.Title = "Index";
}

<h2>Resumes</h2>
<div>
    @Html.ActionLink("Create Resume", "Create", "Resume", null)
</div>
<div>
    <table>
        <thead>
            <tr>
                <td>
                </td>
                <td>Name</td>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.ResumeItems)
            {
                <tr>
                    <td>
                        @Html.ActionLink("View", "Details", "Resume", new { id = item.Id}, null)
                    </td>
                    <td>
                        @item.Name
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>